const availableCategories = [
  "Sports & Leisure",
  "Society & Culture",
  "Science",
  "Music",
  "History",
  "Geography",
  "General knowledge",
  "Food & Drink",
  "Film & TV",
  "Arts & Literature",
];

const sportsLeisure = [
  {
    category: "Sport & Leisure",
    id: "62417d1c0f96c4efe8d773a5",
    correctAnswer: "Edmonton Oilers",
    allOptions: [
      "Edmonton Oilers",
      "Edmonton Steelers",
      "Edmonton Eathquakes",
      "Edmonton Padres",
    ],
    question: "Which of these is a hockey team based in Edmonton?",
    tags: ["canada", "hockey", "nhl"],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "62417d480f96c4efe8d773b7",
    correctAnswer: "Milwaukee Bucks",
    allOptions: [
      "Milwaukee Heat",
      "Milwaukee Reds",
      "Milwaukee Bucks",
      "Milwaukee Pirates",
    ],
    question: "Which of these is a basketball team based in Milwaukee?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "62417dc50f96c4efe8d773e8",
    correctAnswer: "Toronto Raptors",
    allOptions: [
      "Toronto Football",
      "Toronto Islanders",
      "Toronto Falcons",
      "Toronto Raptors",
    ],
    question: "Which of these is a basketball team based in Toronto?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c347cc59eab6f94f893",
    correctAnswer: "Volleyball",
    allOptions: ["Cycling", "Volleyball", "Golf", "Rugby Union"],
    question: "With which sport is Karch Kiraly associated?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "62417da50f96c4efe8d773db",
    correctAnswer: "San Francisco 49ers",
    allOptions: [
      "San Francisco Jaguars",
      "San Francisco 49ers",
      "San Francisco Pistons",
      "San Francisco Predators",
    ],
    question:
      "Which of these is an American Football team based in San Francisco?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c347cc59eab6f94f89c",
    correctAnswer: "Baseball",
    allOptions: ["Baseball", "Rugby Union", "Table tennis", "Cricket"],
    question: "With which sport is Jackie Robinson associated?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "62417d250f96c4efe8d773a9",
    correctAnswer: "Houston Rockets",
    allOptions: [
      "Houston Thunder",
      "Houston A's",
      "Houston Sounders",
      "Houston Rockets",
    ],
    question: "Which of these is a basketball team based in Houston?",
    tags: ["basketball", "nba", "usa"],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c367cc59eab6f9500e2",
    correctAnswer: "8",
    allOptions: ["5", "14", "20", "8"],
    question: "How many fighters are playable in 'Street Fighter II'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c367cc59eab6f9500c2",
    correctAnswer: "15",
    allOptions: ["21", "15", "25", "20"],
    question: "How many points win a game in badminton?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c367cc59eab6f9500aa",
    correctAnswer: "300",
    allOptions: ["100", "200", "300", "250"],
    question:
      "In tenpin bowling, how many points does a perfect game consist of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c347cc59eab6f94f875",
    correctAnswer: "Tennis",
    allOptions: ["Gymnastics", "Cycling", "Swimming", "Tennis"],
    question: "With which sport is Rafael Nadal associated?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c347cc59eab6f94f8b3",
    correctAnswer: "Athletics",
    allOptions: ["Volleyball", "Athletics", "Cricket", "Cycling"],
    question: "With which sport is Jesse Owens associated?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "6242e81d8c2538f9601d2f95",
    correctAnswer: "The Eagles",
    allOptions: ["The Bluebirds", "The Sky Blues", "The Rams", "The Eagles"],
    question:
      "What is the nickname of the English football team Crystal Palace?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "62399eeb43254f1dbcdd082d",
    correctAnswer: "Brazil",
    allOptions: ["Brazil", "France", "Germany", "Uruguay"],
    question:
      "Which country won the 1994 FIFA World Cup, hosted in United States?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "6242e8238c2538f9601d2f97",
    correctAnswer: "The Whites",
    allOptions: ["The Reds", "The Terriers", "The Eagles", "The Whites"],
    question: "What is the nickname of the English football team Leeds United?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "62417cc88c3137686862d73a",
    correctAnswer: "Baltimore Ravens",
    allOptions: [
      "Baltimore Blues",
      "Baltimore Crew",
      "Baltimore Ravens",
      "Baltimore Wizards",
    ],
    question: "Which of these is an American Football team based in Baltimore?",
    tags: ["football", "american_football", "baltimore", "nfl", "usa"],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "62417d890f96c4efe8d773d1",
    correctAnswer: "Phoenix Suns",
    allOptions: [
      "Phoenix Union",
      "Phoenix Heat",
      "Phoenix Bears",
      "Phoenix Suns",
    ],
    question: "Which of these is a basketball team based in Phoenix?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c347cc59eab6f94f8a8",
    correctAnswer: "Golf",
    allOptions: ["Golf", "Table tennis", "Swimming", "Rowing"],
    question: "With which sport is Tiger Woods associated?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c347cc59eab6f94f8b4",
    correctAnswer: "Football",
    allOptions: ["Golf", "Tennis", "Football", "Badminton"],
    question: "With which sport is Johan Cruyff associated?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Sport & Leisure",
    id: "622a1c367cc59eab6f950024",
    correctAnswer: "Tennis",
    allOptions: ["Soccer", "Badminton", "Volleyball", "Tennis"],
    question: "With which sport is Chris Evert Lloyd identified?",
    tags: ["people"],
    type: "Multiple Choice",
  },
];

const societyCulture = [
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fce6",
    correctAnswer: "Austroasiatic",
    allOptions: ["Uralic", "Austroasiatic", "Sino-Tibetan", "Kra–Dai"],
    question: "The language 'Vietnamese' belongs to which language family?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fd01",
    correctAnswer: "W. K. Clifford",
    allOptions: [
      "Thomas Hobbes",
      "Ludwig Wittgenstein",
      "Epictetus",
      "W. K. Clifford",
    ],
    question:
      "Which philosopher famously said 'It is wrong always, everywhere and for everyone, to believe anything upon insufficient evidence'?",
    tags: ["quotes", "philosophy"],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f950124",
    correctAnswer: "In the beginning",
    allOptions: [
      "Praise the lord",
      "In the beginning",
      "Let there be",
      "Hallelujah! Hallelujah! Hallelujah!",
    ],
    question: "What are the first three words of The Bible?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f95012f",
    correctAnswer: "Bull",
    allOptions: ["Horse", "Dolphin", "Eagle", "Bull"],
    question: "In what animal form did Zeus seduce Europa?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f95012c",
    correctAnswer: "December",
    allOptions: ["December", "September", "April", "November"],
    question: "In what month is Christmas observed?",
    tags: ["christmas", "general_knowledge"],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fca5",
    correctAnswer: "Afroasiatic",
    allOptions: ["Afroasiatic", "Indo-European", "Turkic", "Dravidian"],
    question:
      "The language 'Sanaani Spoken Arabic' belongs to which language family?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f95013d",
    correctAnswer: "Isis",
    allOptions: ["Set", "Ammit", "Horus", "Isis"],
    question: "In Egyptian mythology, who was Horus' mother?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fd2c",
    correctAnswer: "Bertrand Russell",
    allOptions: [
      "Thomas Hobbes",
      "Jean-Jacques Rousseau",
      "Bertrand Russell",
      "Ludwig Wittgenstein",
    ],
    question:
      "Which philosopher famously said 'It is undesirable to believe a proposition when there is no ground whatever for supposing it true'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f950131",
    correctAnswer: "Narcissus",
    allOptions: ["Hercules", "Narcissus", "Apollo", "Perseus"],
    question:
      "In Greek mythology, who was the beautiful young man Echo fell in love with?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fd10",
    correctAnswer: "Jean-Paul Sartre",
    allOptions: [
      "Thomas Hobbes",
      "Ludwig Wittgenstein",
      "Jean-Paul Sartre",
      "G. W. F. Hegel",
    ],
    question: "Which philosopher famously said 'Man is condemned to be free'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f950123",
    correctAnswer: "Evil",
    allOptions: ["Shame", "Jewellery", "Mystery", "Evil"],
    question: "What did Pandora release when she opened the box?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fcb1",
    correctAnswer: "Indo-European",
    allOptions: ["Turkic", "Indo-European", "Niger–Congo", "Austronesian"],
    question: "The language 'Assamese' belongs to which language family?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fd32",
    correctAnswer: "Gottfried Wilhelm Leibniz",
    allOptions: [
      "Thomas Hobbes",
      "Denis Diderot",
      "Ludwig Wittgenstein",
      "Gottfried Wilhelm Leibniz",
    ],
    question:
      "Which philosopher famously said 'We live in the best of all possible worlds'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fce0",
    correctAnswer: "Sino-Tibetan",
    allOptions: ["Sino-Tibetan", "Japonic", "Uralic", "Kra–Dai"],
    question: "The language 'Hakka' belongs to which language family?",
    tags: ["language"],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f9500ee",
    correctAnswer: "Fortuna",
    allOptions: ["Tyche", "Fortuna", "Jupiter", "Vesta"],
    question: "Who is the Roman goddess of destiny?",
    tags: ["romans", "mythology", "classics"],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f950127",
    correctAnswer: "Longinus",
    allOptions: ["Atticus", "Augustus", "Longinus", "Tiberius"],
    question:
      "Which Roman soldier pierced the crucified Christ on His side with his spear.",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f95010a",
    correctAnswer: "Oxford University",
    allOptions: ["Oxford University", "Jerusalem", "Cape Town", "Bethlehem"],
    question: "Where was Methodism founded?",
    tags: ["religion"],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f950101",
    correctAnswer: "Zeus",
    allOptions: ["Hephaestus", "Agamemnon", "Achilles", "Zeus"],
    question: "Who was Hercules' father?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c367cc59eab6f9500e5",
    correctAnswer: "Dionysus",
    allOptions: ["Aphrodite", "Isis", "Bacchus", "Dionysus"],
    question: "Who was the Greek god of wine?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Society & Culture",
    id: "622a1c357cc59eab6f94fcb7",
    correctAnswer: "Indo-European",
    allOptions: ["Sino-Tibetan", "Indo-European", "Turkic", "Niger–Congo"],
    question: "The language 'Greek' belongs to which language family?",
    tags: [],
    type: "Multiple Choice",
  },
];

const science = [
  {
    category: "Science",
    id: "622a1c3a7cc59eab6f9510e2",
    correctAnswer: "Wind",
    allOptions: ["Boat", "Wind", "Horse", "Tree"],
    question: 'A "sirocco" refers to a type of __________."',
    tags: ["words"],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3a7cc59eab6f9510bb",
    correctAnswer: "Jurassic",
    allOptions: ["Mesozoic", "Triassic", "Devonian", "Jurassic"],
    question: "In Geology What Period followed The Cretaceous?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3a7cc59eab6f95109f",
    correctAnswer: "Stork",
    allOptions: ["Stork", "Pelican", "Flamingo", "Swan"],
    question:
      "The shoebill __________, native to Africa, is often compared to a statue. The bird will stand perfectly still for long periods waiting for fish to come to surface in the water.",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f9505a2",
    correctAnswer: "plant nutrition and growth in relation to soil conditions",
    allOptions: [
      "existence",
      "dreams",
      "plant nutrition and growth in relation to soil conditions",
      "the study or knowledge of emetics",
    ],
    question: "What is Agrobiology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "62433548cfaae40c12961498",
    correctAnswer: "A Ram",
    allOptions: ["A Jack", "A Drake", "A Rooster", "A Ram"],
    question: "What would you call a male sheep?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "62433564cfaae40c129614a3",
    correctAnswer: "A Cob",
    allOptions: ["A Cob", "A Hob", "A Tiercel", "A Macho"],
    question: "What would you call a male swan?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f9504c2",
    correctAnswer: "one of two main branches of soil science",
    allOptions: [
      "wood",
      "Unidentified flying object phenomena",
      "microorganisms",
      "one of two main branches of soil science",
    ],
    question: "What is Pedology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f950479",
    correctAnswer: "religion",
    allOptions: [
      "religion",
      "measurement",
      "children's behavior and development",
      "blood serum",
    ],
    question: "What is Theology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3f7cc59eab6f9523cc",
    correctAnswer: "Bactrian",
    allOptions: ["Dromedary", "Alpine", "Bactrian", "Bolo"],
    question: "What type of camel has two humps?",
    tags: ["animals", "biology"],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3a7cc59eab6f950fd8",
    correctAnswer: "Kidney",
    allOptions: ["Liver", "Lung", "Kidney", "Brain"],
    question: "Which vital organ does the adjective renal refer to?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3c7cc59eab6f951935",
    correctAnswer: "Radio Carbon Dating",
    allOptions: [
      "Radio Carbon Dating",
      "Olfactory Dating",
      "Magnetic Resonance Dating",
      "Natural Decayance Dating",
    ],
    question: "What Process Is Used For Dating Ancient Organic Objects?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3a7cc59eab6f951089",
    correctAnswer: "Pleiades",
    allOptions: ["Perseids", "Nymphoids", "Sorestas", "Pleiades"],
    question: "Which cluster of stars is also known as the Seven Sisters?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f950539",
    correctAnswer: "the fetus, especially when within the uterus",
    allOptions: [
      "the future",
      "the study and psychology of organisms with regard to their functions and structures",
      "the fetus, especially when within the uterus",
      "bryophytes",
    ],
    question: "What is Fetology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3a7cc59eab6f9510e4",
    correctAnswer: "11 days",
    allOptions: ["11 weeks", "11 hours", "11 days", "11 months"],
    question:
      "Adult polar bears usually eat just the skin and blubber of a seal. They leave the meat for cubs and scavengers. One seal will sustain an adult bear for __________",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "624334c1cfaae40c12961463",
    correctAnswer: "A Calf",
    allOptions: ["A Caterpillar", "A Kit", "A Lamb", "A Calf"],
    question: "What is the word for a young moose?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c3a7cc59eab6f95109a",
    correctAnswer: "Shark",
    allOptions: ["Shark", "Whale", "Dolphin", "Orca"],
    question: "The fins of what sea creature are made into a soup?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f95057f",
    correctAnswer: "the heart",
    allOptions: [
      "past cultures through the analysis of material remains",
      "the heart",
      "Japanese people",
      "ends or final causes",
    ],
    question: "What is Cardiology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f9504a4",
    correctAnswer:
      "the specialty in medicine that deals with diseases of the lungs and the respiratory tract",
    allOptions: [
      "fossil footprints, tracks and burrows",
      "classification",
      "the mathematical study of closeness and connectedness",
      "the specialty in medicine that deals with diseases of the lungs and the respiratory tract",
    ],
    question: "What is Pulmonology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f950505",
    correctAnswer: "waves or wave motions",
    allOptions: [
      "weather",
      "Tibet",
      "waves or wave motions",
      "mental processes in living creatures",
    ],
    question: "What is Kymatology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Science",
    id: "622a1c377cc59eab6f95048c",
    correctAnswer: "the effect of evolution on ethology",
    allOptions: [
      "the medical study of the causation of disease",
      "snakes",
      "wonders, or monsters",
      "the effect of evolution on ethology",
    ],
    question: "What is Sociobiology the study of?",
    tags: [],
    type: "Multiple Choice",
  },
];

const music = [
  {
    category: "Music",
    id: "622a1c347cc59eab6f94fba8",
    correctAnswer: '"Sympathy for the Devil" by the Rolling Stones',
    allOptions: [
      '"Welcome to the Black Parade" by My Chemical Romance',
      '"Crazy Train" by Ozzy Osbourne',
      '"Baby Got Back" by Sir Mix-a-Lot',
      '"Sympathy for the Devil" by the Rolling Stones',
    ],
    question:
      "Which song begins with the lyrics: \"Please allow me to introduce myself / I'm a man of wealth and taste / I've been around for a long, long year / Stole many a man's soul and faith...\"?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c357cc59eab6f94feb5",
    correctAnswer: "Beyoncé",
    allOptions: ["Madonna", "Drake", "Nicki Minaj", "Beyoncé"],
    question:
      "Which American singer, actress and record producer released the studio album '4'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c397cc59eab6f950da4",
    correctAnswer: "Led Zeppelin",
    allOptions: ["Led Zeppelin", "Cocteau Twins", "Lostprophets", "The Kinks"],
    question: "Which band includes 'John Bonham'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c397cc59eab6f950d7c",
    correctAnswer: "Judas Priest",
    allOptions: [
      "Arctic Monkeys",
      "Judas Priest",
      "Feeder",
      "Bring Me the Horizon",
    ],
    question: "Which band includes 'Rob Halford'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c387cc59eab6f950b63",
    correctAnswer: "Big Bang",
    allOptions: ["Red Velvet", "2PM", "Big Bang", "BTS"],
    question: "Which band includes 'G-Dragon'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c397cc59eab6f950cf1",
    correctAnswer: "Queen",
    allOptions: ["Level 42", "Queen", "Deep Purple", "Feeder"],
    question: "Which British rock band released the album 'Made in Heaven'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c357cc59eab6f94fdd3",
    correctAnswer: "Ed Sheeran",
    allOptions: ["Mika", "Morrissey", "Dido", "Ed Sheeran"],
    question: "Which English singer-songwriter released the studio album '÷'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c387cc59eab6f950b7a",
    correctAnswer: "The Offspring",
    allOptions: [
      "The Offspring",
      "Styx",
      "Three 6 Mafia",
      "The Velvet Underground",
    ],
    question:
      "Which punk band from the United States released the studio album 'Rise and Fall, Rage and Grace'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c397cc59eab6f950da1",
    correctAnswer: "Iron Maiden",
    allOptions: ["Deep Purple", "Feeder", "Squeeze", "Iron Maiden"],
    question: "Which band includes 'Adrian Smith'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c357cc59eab6f94ff64",
    correctAnswer: "Queen",
    allOptions: ["Feeder", "The Clash", "Queen", "Pink Floyd"],
    question:
      "Which British rock band released the single 'Another One Bites the Dust'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c397cc59eab6f950d50",
    correctAnswer: "One Direction",
    allOptions: [
      "One Direction",
      "Level 42",
      "Orchestral Manoeuvres in the Dark",
      "Blur",
    ],
    question: "Which band includes 'Louis Tomlinson'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c387cc59eab6f950b9e",
    correctAnswer: "Wings",
    allOptions: ["Level 42", "Deep Purple", "The Chemical Brothers", "Wings"],
    question: "Which band includes 'Paul McCartney'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c3d7cc59eab6f951c7d",
    correctAnswer: "Eagles",
    allOptions: ["Led Zeppelin", "Black Sabbath", "Eagles", "Aerosmith"],
    question: "'Witchy Woman' was a hit for which rock group in the 1970's?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c357cc59eab6f94fdd0",
    correctAnswer: "Megadeath",
    allOptions: ["Metallica", "Megadeath", "Slayer", "Sodom"],
    question: "Name The Thrash Metal Band Headed By Guitarist Dave Mustaine",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c387cc59eab6f950b74",
    correctAnswer: "Van Halen",
    allOptions: [
      "Deep Purple",
      "The Pussycat Dolls",
      "Van Halen",
      "Three 6 Mafia",
    ],
    question: "Which American heavy metal band released the song 'Jump'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c387cc59eab6f950b0a",
    correctAnswer: "Matia Bazar",
    allOptions: [
      "Matia Bazar",
      "Elio e le Storie Tese",
      "Wess and Dori Ghezzi",
      "Litfiba",
    ],
    question: "Which band includes 'Antonella Ruggiero'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c347cc59eab6f94fbab",
    correctAnswer: '"Lose Yourself" by Eminem',
    allOptions: [
      "\"Jumpin', Jumpin'\" by Destiny's Child",
      '"What I Got" by Sublime',
      '"Basket Case" by Green Day',
      '"Lose Yourself" by Eminem',
    ],
    question:
      'Which song begins with the lyrics: "Look / If you had / One shot / Or one opportunity / To seize everything you ever wanted / In one moment / Would you capture it / Or just let it slip?"?',
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c397cc59eab6f950d91",
    correctAnswer: "Red Hot Chili Peppers",
    allOptions: [
      "The Monkees",
      "Black Flag",
      "Journey",
      "Red Hot Chili Peppers",
    ],
    question: "Which band includes 'Anthony Kiedis'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c377cc59eab6f950458",
    correctAnswer: "A Button",
    allOptions: ["A Carrot", "Snow", "A Button", "An Icicle"],
    question:
      "According to the lyrics of the famous Christmas song, what was Frosty The Snowman's nose made from?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Music",
    id: "622a1c387cc59eab6f950b0d",
    correctAnswer: "Tangerine Dream",
    allOptions: ["Scooter", "Grave Digger", "Oomph!", "Tangerine Dream"],
    question: "Which band includes 'Klaus Schulze'?",
    tags: [],
    type: "Multiple Choice",
  },
];

const history = [
  {
    category: "History",
    id: "622a1c3c7cc59eab6f951a16",
    correctAnswer: "Marc Antony",
    allOptions: ["Marc Antony", "Lepidus", "Marcus Crassus", "Pompey"],
    question: "Which Roman killed himself after his defeat at Actium?",
    tags: ["battles", "romans", "people"],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c3c7cc59eab6f951a2d",
    correctAnswer: "Parthenon",
    allOptions: ["Colosseum", "Vivarium", "Academy", "Parthenon"],
    question: "Which of these is a building in the acropolis of Athens?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c3c7cc59eab6f9519b2",
    correctAnswer: "Radiation poisoning",
    allOptions: [
      "Drowning",
      "She was hit by a car",
      "Radiation poisoning",
      "She was struck by lightning",
    ],
    question: "What did Marie Curie die of on 4th July, 1934?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f9503c3",
    correctAnswer: "Raoul",
    allOptions: ["Pedro", "Raoul", "Mikel", "Sergio"],
    question: "What's fidel castro's brother's name? ",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f950344",
    correctAnswer: "Catherine Of Aragon",
    allOptions: [
      "Anne Boleyn",
      "Anne Howard",
      "Catherine Of Aragon",
      "Catherine Parr",
    ],
    question: "Who Was The 1st wife of henry VIII? ",
    tags: ["kings", "uk", "medieval", "middle_ages", "people"],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c377cc59eab6f950439",
    correctAnswer: "Nine",
    allOptions: ["One", "Two", "Six", "Nine"],
    question: "How Many Crusades Were There?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c3c7cc59eab6f951ac4",
    correctAnswer: "Calypso",
    allOptions: ["Calypso", "Discovery", "Terra Nova", "Beagle"],
    question: "What was the name of Jacques Cousteau's research ship?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c3c7cc59eab6f951b37",
    correctAnswer: "1789",
    allOptions: ["1890", "1921", "1712", "1789"],
    question: "In What Year Was The French Declaration Of The Rights Of Man?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c3d7cc59eab6f951bef",
    correctAnswer: "General Custer",
    allOptions: [
      "General Lee",
      "General Grant",
      "General Custer",
      "General Nelson",
    ],
    question: "Who was defeated at the Battle of Little Bighorn?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f95037b",
    correctAnswer: "Henry II",
    allOptions: ["William I", "Richard III", "Henry II", "Henry VIII"],
    question: 'Who Said "Will No-One Rid Me Of This Turbulent Priest"?',
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c357cc59eab6f94fd41",
    correctAnswer: "Constantine",
    allOptions: ["Constantine", "Byzantine", "Marcus Aurelius", "Trajan"],
    question:
      "Which Roman Emperor moved the capital from Rome to the city now known as Istanbul? ",
    tags: ["romans", "classics"],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f9503f5",
    correctAnswer: "Hawaii",
    allOptions: ["Alaska", "Puerto Rico", "New Mexico", "Hawaii"],
    question: "What Became America's 50th State On August 21st 1959?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f950320",
    correctAnswer: "Gamal Abdul Nasser",
    allOptions: [
      "Gamal Abdul Nasser",
      "Ahmed Sabzi",
      "Omar Sharif",
      "Asser Yasin",
    ],
    question:
      "Who was the President of Egypt in 1956 who nationalized the Suez Canal, causing British and French troops to invade the region?",
    tags: ["wars", "politics"],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c347cc59eab6f94f9aa",
    correctAnswer: "Elizabeth I",
    allOptions: ["James II", "Richard I", "Henry II", "Elizabeth I"],
    question:
      "Who was the monarch of England during the time period 1558-1603?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c377cc59eab6f950437",
    correctAnswer: "The Royal Family",
    allOptions: [
      "The Kardashians",
      "The Osmonds",
      "The Royal Family",
      "The Gibbs",
    ],
    question:
      "In 1969 Richard Cawston Made A Documentary For The BBC About Which Famous Family?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c3c7cc59eab6f951a41",
    correctAnswer: "Ghana",
    allOptions: ["Ghana", "India", "Australia", "Egypt"],
    question:
      "The Gold Coast gained its independence from Great Britain in 1957 and formed part of which new country?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f95036d",
    correctAnswer: "Marie Antoinette",
    allOptions: [
      "Queen Victoria",
      "Abraham Lincoln",
      "Marie Antoinette",
      "Cleopatra",
    ],
    question: 'Who is reputed to have said said: "Let them eat cake"?',
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f950357",
    correctAnswer: "George A. Custer",
    allOptions: [
      "Erwin Rommel",
      "Hannibal",
      "William T. Sherman",
      "George A. Custer",
    ],
    question: "Who was defeated at the Battle of Little Bighorn?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f95031c",
    correctAnswer: "Boudica",
    allOptions: ["Joan of Arc", "Zenobia", "Fulvia", "Boudica"],
    question:
      "Who Was the Queen Of The Iceni Tribe Of England Who Led An Uprising Against The Romans?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "History",
    id: "622a1c367cc59eab6f950347",
    correctAnswer: "Dwight Eisenhower",
    allOptions: [
      "Franklin Roosevelt",
      "Dwight Eisenhower",
      "Lyndon Johnson",
      "Jimmy Carter",
    ],
    question: "Who was President of the USA from 1953 till 1961?",
    tags: [],
    type: "Multiple Choice",
  },
];

const geography = [
  {
    category: "Geography",
    id: "623741c3cb85f7ce9e949d87",
    correctAnswer: "Norway",
    allOptions: ["Finland", "Norway", "Sweden", "Denmark"],
    question: "Oslo is the capital city of which country?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c357cc59eab6f94ffa9",
    correctAnswer: "Venice",
    allOptions: ["Rome", "Milan", "Venice", "Naples"],
    question: "In which city would you find the Bridge of Sighs?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c387cc59eab6f9507f5",
    correctAnswer: "Oceania",
    allOptions: ["South America", "Oceania", "Europe", "Asia"],
    question: "The country of Samoa is on which continent?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c387cc59eab6f950a1a",
    correctAnswer: "France",
    allOptions: ["France", "Luxembourg", "Denmark", "Switzerland"],
    question: "Which of these countries borders Kingdom of the Netherlands?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c357cc59eab6f950000",
    correctAnswer: "Burkina Faso",
    allOptions: ["Ghana", "Mali", "Togo", "Burkina Faso"],
    question: "Ouagadougou is the capital of ______?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "623742becb85f7ce9e949dec",
    correctAnswer: "Funafuti",
    allOptions: ["Sana'a", "Funafuti", "Manama", "Kigali"],
    question: "What is the capital city of Tuvalu?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "62373fc0cb85f7ce9e949cb8",
    correctAnswer: "Brasilia",
    allOptions: ["São Paulo", "Rio de Janeiro", "Brasilia", "Manaus"],
    question: "What is the capital city of Brazil?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "62374186cb85f7ce9e949d6f",
    correctAnswer: "Mozambique",
    allOptions: [
      "Burkina Faso",
      "Sao Tome and Principe",
      "Micronesia",
      "Mozambique",
    ],
    question: "Maputo is the capital city of which country?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "6237373ccfe13103f55eb5a0",
    correctAnswer: "Zimbabwe",
    allOptions: ["Zambia", "The Netherlands", "Zimbabwe", "Western Sahara"],
    question:
      "Which region of the world uses '.zw' at the end of its web addresses?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c357cc59eab6f94ffdd",
    correctAnswer: "Bamako",
    allOptions: ["Bamako", "Dakar", "Accra", "Kumasi"],
    question: "What is the capital of Mali?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "623388210161109f922aac69",
    correctAnswer: "International Date Line",
    allOptions: [
      "The Equator",
      "The Prime Meridian",
      "The Blood Meridian",
      "International Date Line",
    ],
    question:
      "Which imaginery line approximately follows the 180 degree meridian through the Pacific Ocean?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "623b585cfd6c701a921183b4",
    correctAnswer: "Indonesia",
    allOptions: ["Tanzania", "Indonesia", "Malta", "Brazil"],
    question:
      "In which country would you find the UNESCO World Heritage site of Prambanan?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c387cc59eab6f950a05",
    correctAnswer: "Saudi Arabia",
    allOptions: ["Djibouti", "Somalia", "Saudi Arabia", "Eritrea"],
    question: "Which of these countries borders Yemen?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c357cc59eab6f94fdf2",
    correctAnswer: "Plate Tectonics ",
    allOptions: [
      "Tectologic Deformation",
      "Terra Firma",
      "Terestial Convection",
      "Plate Tectonics ",
    ],
    question: "Which Theory Is Used To Explain Continental Drift?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c387cc59eab6f950a83",
    correctAnswer: "Bolivia",
    allOptions: ["Trinidad and Tobago", "Chile", "Bolivia", "Grenada"],
    question: "Which of these countries borders Brazil?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "62374029cb85f7ce9e949ce2",
    correctAnswer: "Nicosia",
    allOptions: ["Nicosia", "Riga", "Dodoma", "Port-au-Prince"],
    question: "What is the capital city of Cyprus?",
    tags: ["capital_cities"],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c387cc59eab6f950ab5",
    correctAnswer: "Ukraine",
    allOptions: ["Kyrgyzstan", "Ukraine", "Tajikistan", "Uzbekistan"],
    question: "Which of these countries borders Russia?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c387cc59eab6f950acd",
    correctAnswer: "Bhutan",
    allOptions: ["Tajikistan", "Kyrgyzstan", "Bhutan", "Thailand"],
    question: "Which of these countries borders India?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "622a1c387cc59eab6f950a6e",
    correctAnswer: "Italy",
    allOptions: ["Croatia", "Italy", "San Marino", "Bosnia and Herzegovina"],
    question: "Which of these countries borders Austria?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Geography",
    id: "62373600cfe13103f55eb590",
    correctAnswer: "United Arab Emirates",
    allOptions: ["United Arab Emirates", "Faeroe Islands", "Israel", "Armenia"],
    question:
      "Which region of the world uses '.ae' at the end of its web addresses?",
    tags: [],
    type: "Multiple Choice",
  },
];

const generalKnowledge = [
  {
    category: "General Knowledge",
    id: "622a1c3d7cc59eab6f951c3a",
    correctAnswer: "Testicles",
    allOptions: ["Eyes", "Fists", "Arms", "Testicles"],
    question:
      "'Christmas Crackers' is cockney rhyming slang for which body part?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c3a7cc59eab6f951043",
    correctAnswer: "Lesser Lion",
    allOptions: ["Iron Lion", "Lesser Lion", "Ferocious Lion", "Brave Lion"],
    question:
      "What is the meaning of the name of the constellation Leo Minor ?",
    tags: ["astronomy"],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c377cc59eab6f95045c",
    correctAnswer: "7 Swans A Swimming",
    allOptions: [
      "7 Maids a Milking",
      "7 Lords A Leaping",
      "7 Drummers Drumming",
      "7 Swans A Swimming",
    ],
    question:
      'What did my true love give to me on the "Seventh" day of Christmas"?',
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c397cc59eab6f950fb2",
    correctAnswer: "The Lumiere Brothers",
    allOptions: [
      "The Lumiere Brothers",
      "The Warner Brothers",
      "The Cannes Brothers",
      "The Canal Brothers",
    ],
    question: "Who Opened The First Cinema In Paris In 1895?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "6239f8099129041bf3925cc0",
    correctAnswer: "Delta",
    allOptions: ["Dog", "Delta", "Danube", "Dig"],
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter D?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc83",
    correctAnswer: "Fipple",
    allOptions: ["Smicker", "Bibble", "Fipple", "Firman"],
    question:
      "Which word is defined as 'the mouthpiece of a recorder or similar wind instrument'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc62",
    correctAnswer: "Poppycock",
    allOptions: ["Dipthong", "Poppycock", "Ragamuffin", "Quomodocunquizing"],
    question: "Which word is defined as 'nonsense'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c367cc59eab6f9503d3",
    correctAnswer: "The Hula Hoop",
    allOptions: ["The Hula Hoop", "Rubix Cube", "Slinky", "Pog"],
    question:
      "What toy was released in 1957, creating an instant craze among children?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc55",
    correctAnswer: "Winklepicker",
    allOptions: ["Tittynope", "Dipthong", "Finifugal", "Winklepicker"],
    question:
      "Which word is defined as 'style of shoe or boot in the 1950s with a sharp and long pointed toe'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc8b",
    correctAnswer: "Doodle Sack",
    allOptions: ["Doodle Sack", "Fipple", "Tittynope", "Quire"],
    question: "Which word is defined as 'Old English word for bagpipe'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc89",
    correctAnswer: "Dragoman",
    allOptions: ["Smicker", "Grommet", "Ragamuffin", "Dragoman"],
    question:
      "Which word is defined as 'an interpreter or professional guide for travelers'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c367cc59eab6f95031a",
    correctAnswer: "Robert Burns",
    allOptions: [
      "Robert Burns",
      "JM Barrie",
      "Robert Louis Stevenson",
      "James Hogg",
    ],
    question: "Who wrote Auld Lange Syne?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc73",
    correctAnswer: "Impignorate",
    allOptions: ["Dipthong", "Deipnophobia", "Impignorate", "Erf"],
    question: "Which word is defined as 'to pawn or mortgage something'?",
    tags: ["words"],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc9a",
    correctAnswer: "Agastopia",
    allOptions: ["Dragoman", "Agastopia", "Oxter", "Jentacular"],
    question:
      "Which word is defined as 'admiration of a particular part of someone’s body'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc7f",
    correctAnswer: "Funambulist",
    allOptions: ["Funambulist", "Gubbins", "Kerfuffle", "Hullaballoo"],
    question: "Which word is defined as 'a tightrope walker'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "6239f82ea72e7a347ac879d4",
    correctAnswer: "Romeo",
    allOptions: ["Rwanda", "Roar", "Rowboat", "Romeo"],
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter R?",
    tags: ["language", "general_knowledge"],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c3d7cc59eab6f951c6a",
    correctAnswer: "Little Jack Horner",
    allOptions: [
      "Humpty Dumpty",
      "Jack",
      "Happy Hungry Harry",
      "Little Jack Horner",
    ],
    question:
      "According to the nursery rhyme, who, 'sat in the corner eating a Christmas Pie''?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fc84",
    correctAnswer: "Finifugal",
    allOptions: ["Groke", "Finifugal", "Gabelle", "Salopettes"],
    question: "Which word is defined as 'afraid of finishing anything'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "622a1c357cc59eab6f94fe2c",
    correctAnswer: "Krona",
    allOptions: ["Franc", "Mark", "Krona", "Pund"],
    question:
      "Before the Euro, what was the basic unit of currency for Iceland?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "General Knowledge",
    id: "6239f8019129041bf3925cbd",
    correctAnswer: "Alpha",
    allOptions: ["Alpha", "Apple", "Animal", "Aeroplan"],
    question:
      "What word is used in the NATO Phonetic Alphabet for the letter A?",
    tags: [],
    type: "Multiple Choice",
  },
];

const foodDrink = [
  {
    category: "Food & Drink",
    id: "622a1c3b7cc59eab6f951640",
    correctAnswer: "Sugar Cane",
    allOptions: ["Banana Tree", "Sugar Cane", "Tobacco", "Palm Tree"],
    question: "From which plant is Rum made?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "624ab0a5348a461bfc67068b",
    correctAnswer: "Africa",
    allOptions: [
      "The Middle East",
      "Central America",
      "Africa",
      "North America",
    ],
    question: "Where in the world are yams originally from?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c3a7cc59eab6f951059",
    correctAnswer: "Melon",
    allOptions: ["Grape", "Apple", "Orange", "Melon"],
    question: "What Fruit Is A Cantaloupe?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f950286",
    correctAnswer: "Courgette ",
    allOptions: ["Courgette ", "Carrot", "Onion", "Cucumber"],
    question: "What vegetable is known a zucchini in the USA?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "624ab0e1348a461bfc6706a2",
    correctAnswer: "Southeast Asia",
    allOptions: ["China", "Southeast Asia", "South America", "Central Asia"],
    question: "From which part of the world do oranges originate?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f95029f",
    correctAnswer: "Parmesan ",
    allOptions: ["Wensleydale", "Stilton", "Parmesan ", "Gorgonzola"],
    question: "What sort of cheese would you sprinkle on spaghetti?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c3b7cc59eab6f9515a2",
    correctAnswer: "Three ",
    allOptions: ["Two", "Four", "Five", "Three "],
    question: "How many pieces of bun are in a Mcdonald's Big Mac?",
    tags: ["food"],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "624c60c095b12387e142c79b",
    correctAnswer: "Ramen",
    allOptions: ["Ramen", "Ceviche", "Plov", "Chilli Crab"],
    question: "Which of these dishes would you most expect to find in Japan?",
    tags: ["food"],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c3a7cc59eab6f95105c",
    correctAnswer: "Grapefruit",
    allOptions: ["Lemon", "Pineapple", "Grapefruit", "Blood Orange"],
    question: 'What fruit bears the latin name "citrus grandis"?',
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f9502da",
    correctAnswer: "Lamb ",
    allOptions: ["Lamb ", "Beef", "Pork", "Chicken"],
    question: "Traditionally what type of meat is used to make a mousakka?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f950299",
    correctAnswer: "Pancakes ",
    allOptions: ["Lamb", "Fish", "Simnel Cake", "Pancakes "],
    question: "What Traditionally Might You Eat On Shrove Tuesday?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "624ab077c64ce21c11f06e9e",
    correctAnswer: "South America",
    allOptions: ["The Middle East", "South America", "Central Asia", "Europe"],
    question: "From which part of the world do lima beans originate?",
    tags: ["food"],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f950242",
    correctAnswer: "Bergamot ",
    allOptions: ["Lavender", "Lemon", "Bergamot ", "Saffron"],
    question: "Which ingredient gives Earl Grey tea its distinctive flavour?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f9502c6",
    correctAnswer: "Spiced Ham ",
    allOptions: [
      "Special Made Artifial Meat",
      "Superior Manufactured Artificial Meat",
      "Special Ham",
      "Spiced Ham ",
    ],
    question: "What Is 'SPAM' Short For?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f9502ec",
    correctAnswer: "Dry ",
    allOptions: ["Sweet", "Dry ", "Fruity", "Light"],
    question: "If A Sparkling Wine Is Labelled As 'Brut' How Will It Taste?",
    tags: ["drink"],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f95029b",
    correctAnswer: "Mozzarella ",
    allOptions: ["Gorgonzola", "Parmezan", "Mozzarella ", "Gouda"],
    question: "What Type Of Cheese Is Traditionally Made From Buffaloes Milk?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "624c609150d1a5e051325a64",
    correctAnswer: "Moussaka",
    allOptions: ["Moussaka", "Verivorst", "Wiener Schnitzel", "Chicken Adobo"],
    question: "Which of these dishes is most associated with Greece?",
    tags: ["food"],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f950277",
    correctAnswer: "The United States",
    allOptions: ["Korea", "China", "Germany", "The United States"],
    question: "Where were fortune cookies invented?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c367cc59eab6f950249",
    correctAnswer: "Avocado",
    allOptions: ["Mango", "Banana", "Avocado", "Pineapple"],
    question: "Which fruit has the most calories per gram?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Food & Drink",
    id: "622a1c3b7cc59eab6f951601",
    correctAnswer: "Sturgeon ",
    allOptions: ["Sturgeon ", "Salmon", "Trout", "Herring"],
    question: "Which fish does caviar come from? ",
    tags: ["fish", "food"],
    type: "Multiple Choice",
  },
];

const filmTv = [
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fc12",
    correctAnswer: '"What a dump."',
    allOptions: [
      '"May the odds ever be in your favor."',
      '"We’re goin’ streaking!"',
      '"What a dump."',
      '"Mother of mercy, is this the end of Rico?"',
    ],
    question: "Which of these quotes is from the film 'Beyond the Forest'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fb6c",
    correctAnswer: "Gentleman's Agreement",
    allOptions: [
      "Gentleman's Agreement",
      "The Bishop's Wife",
      "Crossfire",
      "Great Expectations",
    ],
    question: "Which film won the Academy Award for Best Picture in 1947?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fae8",
    correctAnswer: "Paul Newman",
    allOptions: ["Dexter Gordon", "Paul Newman", "Bob Hoskins", "William Hurt"],
    question:
      "Who won the 1986 Academy Award for Best Leading Actor for playing the role of Eddie Felson in The Color of Money?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c357cc59eab6f94fc3e",
    correctAnswer: '"E.T. phone home."',
    allOptions: [
      '"There\'s no place like home."',
      '"I’ve been a poor man and I’ve been a rich man. And I choose rich every f****** time!"',
      '"A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti."',
      '"E.T. phone home."',
    ],
    question:
      "Which of these quotes is from the film 'E.T.: The Extra-Terrestrial'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f950788",
    correctAnswer: "George Clooney",
    allOptions: [
      "Sean Connery",
      "Gary Oldman",
      "George Clooney",
      "Ewan McGregor",
    ],
    question: "Which actor has featued in films including ER and Gravity?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f950721",
    correctAnswer: "Kirsten Dunst",
    allOptions: [
      "Charlize Theron",
      "Emma Thompson",
      "Helen Mirren",
      "Kirsten Dunst",
    ],
    question:
      "Which actor has featued in films including Fargo and Spider-Man?",
    tags: ["acting", "film"],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f950618",
    correctAnswer: "Zoe Saldana",
    allOptions: [
      "Catherine Deneuve",
      "Zoe Saldana",
      "Audrey Hepburn",
      "Rachel Weisz",
    ],
    question:
      "Which actor has featued in films including Avengers: Endgame and Avatar?",
    tags: ["acting", "film"],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fbd0",
    correctAnswer: '"My precious."',
    allOptions: [
      '"My precious."',
      '"Keep your friends close, but your enemies closer."',
      '"You\'re gonna need a bigger boat."',
      '"You shall not pass!"',
    ],
    question:
      "Which of these quotes is from the film 'Lord of the Rings: The Two Towers'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f9507d1",
    correctAnswer: "Morgan Freeman",
    allOptions: [
      "Christopher Lee",
      "Liam Neeson",
      "Morgan Freeman",
      "Arnold Schwarzenegger",
    ],
    question:
      "Which actor has featued in films including Batman Begins and Lucy?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c367cc59eab6f950202",
    correctAnswer: "Michael Bay",
    allOptions: [
      "Steven Spielberg",
      "Michael Bay",
      "Woody Allen",
      "Martin Scorsese",
    ],
    question: "Which director directed Transformers?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f950700",
    correctAnswer: "Sandra Bæ Hovedr",
    allOptions: [
      "Charlize Theron",
      "Emma Thompson",
      "Maggie Smith",
      "Sandra Bæ Hovedr",
    ],
    question: "Which actor has featued in films including Gravity and Speed?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f950625",
    correctAnswer: "Jennifer Lawrence",
    allOptions: [
      "Jennifer Lawrence",
      "Catherine Deneuve",
      "Audrey Hepburn",
      "Rachel Weisz",
    ],
    question:
      "Which actor has featued in films including X-Men: Days of Future Past and American Hustle?",
    tags: ["acting", "film"],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c367cc59eab6f9501f9",
    correctAnswer: "Peter Jackson",
    allOptions: [
      "Steven Spielberg",
      "Woody Allen",
      "Peter Jackson",
      "Martin Scorsese",
    ],
    question:
      "Which director directed The Lord of the Rings: The Fellowship of the Ring?",
    tags: ["film"],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94f935",
    correctAnswer: "Sweet Smell of Success",
    allOptions: [
      "Network",
      "It's A Wonderful Life",
      "Sweet Smell of Success",
      "The Shining",
    ],
    question: "Which film contains the character 'J. J. Hunsecker'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f950719",
    correctAnswer: "Kathy Bates",
    allOptions: ["Maggie Smith", "Helen Mirren", "Kate Winslet", "Kathy Bates"],
    question:
      "Which actor has featued in films including American Horror Story and Titanic?",
    tags: ["acting"],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fafe",
    correctAnswer: "Sandra Bullock",
    allOptions: [
      "Sandra Bullock",
      "Helen Mirren",
      "Carey Mulligan",
      "Gabourey Sidibe",
    ],
    question:
      "Who won the 2009 Academy Award for Best Leading Actress for playing the role of Leigh Anne Tuohy in The Blind Side?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fa90",
    correctAnswer: "Viola Davis",
    allOptions: [
      "Naomie Harris",
      "Nicole Kidman",
      "Octavia Spencer",
      "Viola Davis",
    ],
    question:
      "Who won the 2016 Academy Award for Best Supporting Actress for playing the role of Rose Maxson in Fences?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fc02",
    correctAnswer: '"I have always depended on the kindness of strangers."',
    allOptions: [
      '"A boy\'s best friend is his mother."',
      '"I have always depended on the kindness of strangers."',
      '"Oh what a day. What a lovely day!"',
      "\"Wait a minute, wait a minute. You ain't heard nothin' yet!\"",
    ],
    question:
      "Which of these quotes is from the film 'A Streetcar Named Desire'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c347cc59eab6f94fb06",
    correctAnswer: "Helen Mirren",
    allOptions: ["Penélope Cruz", "Helen Mirren", "Judi Dench", "Meryl Streep"],
    question:
      "Who won the 2006 Academy Award for Best Leading Actress for playing the role of The Queen in The Queen?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Film & TV",
    id: "622a1c377cc59eab6f950797",
    correctAnswer: "Robert Downey Jr.",
    allOptions: [
      "Chris Evans",
      "Chris Hemsworth",
      "Robert Downey Jr.",
      "Tom Holland",
    ],
    question:
      "Which actor played the role of Iron Man in the Marvel Cinematic Universe?",
    tags: ["acting", "film", "marvel", "comics", "mcu"],
    type: "Multiple Choice",
  },
];

const artsLiterature = [
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950e98",
    correctAnswer: "Friedrich Schiller",
    allOptions: [
      "Sebastian Brant",
      "Agatha Christie",
      "Friedrich Schiller",
      "Rainer Maria Rilke",
    ],
    question: "Which author wrote 'The Robbers'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c367cc59eab6f9501bf",
    correctAnswer: "The Great Gatsby",
    allOptions: [
      "The Shining",
      "The Great Gatsby",
      "The Silmarillion",
      "American Psycho (book)",
    ],
    question:
      "Which piece of written work starts with the line 'In my younger and more vulnerable years my father gave me some advice that I’ve been turning over in my mind ever since.'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c347cc59eab6f94f97b",
    correctAnswer: "All the King's Men",
    allOptions: [
      "Gone With the Wind",
      "Lonesome Dove",
      "Love in the Time of Cholera",
      "All the King's Men",
    ],
    question: "Which book contains the character 'Willie Stark'?",
    tags: ["literature"],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c347cc59eab6f94f9fd",
    correctAnswer: "Sandro Botticelli",
    allOptions: [
      "Sandro Botticelli",
      "Leonardo da Vinci",
      "‎Salvador Dalí",
      "‎Vincent van Gogh",
    ],
    question: 'Which artist painted "The Birth of Venus"',
    tags: ["painting", "art"],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950eba",
    correctAnswer: "Oscar Wilde",
    allOptions: [
      "Charles Dickens",
      "G. K. Chesterton",
      "Oscar Wilde",
      "Alphonse Daudet",
    ],
    question: "Which author wrote 'The Happy Prince and Other Tales'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950f5c",
    correctAnswer: "Isaac Asimov",
    allOptions: [
      "Isaac Asimov",
      "Ursula K. Le Guin",
      "Philip K. Dick",
      "Stephen King",
    ],
    question: "Which author wrote 'Pebble in the Sky'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950ecb",
    correctAnswer: "Walter Scott",
    allOptions: [
      "Walter Scott",
      "Oscar Wilde",
      "J. R. R. Tolkien",
      "Alphonse Daudet",
    ],
    question: "Which author wrote 'Ivanhoe'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950ec5",
    correctAnswer: "James Joyce",
    allOptions: [
      "Samuel Beckett",
      "Oscar Wilde",
      "Walter Scott",
      "Jonathan Swift",
    ],
    question: "Which author wrote 'Dubliners'?",
    tags: ["literature", "classic_novels"],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950f15",
    correctAnswer: "Giovanni Boccaccio",
    allOptions: [
      "Dante Alighieri",
      "Agatha Christie",
      "Stephenie Meyer",
      "Giovanni Boccaccio",
    ],
    question: "Which author wrote 'The Decameron'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950e14",
    correctAnswer: "Dan Brown",
    allOptions: ["Stephen King", "Donna Leon", "Dan Brown", "Frederik Pohl"],
    question: "Which author wrote 'The Da Vinci Code'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950e2d",
    correctAnswer: "L. Frank Baum",
    allOptions: [
      "L. Frank Baum",
      "Suzanne Collins",
      "James Fenimore Cooper",
      "Donna Leon",
    ],
    question: "Which author wrote 'The Wonderful Wizard of Oz'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c347cc59eab6f94fa08",
    correctAnswer: "Henri Rousseau",
    allOptions: [
      "Raphael",
      "‎Pablo Picasso",
      "Vasily Kandinsky",
      "Henri Rousseau",
    ],
    question: 'Which artist painted "The Sleeping Gypsy"',
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950dd4",
    correctAnswer: "Meg Cabot",
    allOptions: [
      "Stephenie Meyer",
      "Philip K. Dick",
      "Meg Cabot",
      "Brandon Sanderson",
    ],
    question: "Which author wrote 'The Princess Diaries'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950e41",
    correctAnswer: "Mikhail Bulgakov",
    allOptions: [
      "Mikhail Bulgakov",
      "Vladimir Nabokov",
      "Ayn Rand",
      "Stanisław Lem",
    ],
    question: "Which author wrote 'Heart of a Dog'?",
    tags: ["literature"],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c3a7cc59eab6f951094",
    correctAnswer: "Dog",
    allOptions: ["Horse", "Goat", "Dog", "Ghost"],
    question:
      'The only __________ to ever appear in a Shakespearean play was Crab in "The Two Gentlemen of Verona."',
    tags: ["shakespeare", "theater"],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950e1d",
    correctAnswer: "Marcel Proust",
    allOptions: [
      "François-René de Chateaubriand",
      "Umberto Eco",
      "Alexandre Dumas",
      "Marcel Proust",
    ],
    question: "Which author wrote 'In Search of Lost Time'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c347cc59eab6f94fa30",
    correctAnswer: "Renaissance",
    allOptions: ["Art Nouveau", "Romanticism", "Cubism", "Renaissance"],
    question:
      "The Sistine Chapel ceiling painting by Michelangelo is a part of which art movement?",
    tags: ["art", "painting"],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c367cc59eab6f9501c3",
    correctAnswer: "Harry Potter and the Deathly Hallows",
    allOptions: [
      "The Sea of Monsters",
      "The Battle of the Labyrinth",
      "The Mysterious Island",
      "Harry Potter and the Deathly Hallows",
    ],
    question:
      "Which piece of written work starts with the line 'The two men appeared out of nowhere, a few yards apart in the narrow, moonlit lane.'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950ed3",
    correctAnswer: "Walter Scott",
    allOptions: [
      "Walter Scott",
      "Oscar Wilde",
      "J. R. R. Tolkien",
      "Alphonse Daudet",
    ],
    question: "Which author wrote 'The Heart of Midlothian'?",
    tags: [],
    type: "Multiple Choice",
  },
  {
    category: "Arts & Literature",
    id: "622a1c397cc59eab6f950dde",
    correctAnswer: "Mikhail Sholokhov",
    allOptions: [
      "Ivan Turgenev",
      "Henryk Sienkiewicz",
      "Mikhail Sholokhov",
      "Leo Tolstoy",
    ],
    question: "Which author wrote 'And Quiet Flows the Don'?",
    tags: [],
    type: "Multiple Choice",
  },
];

export {
  sportsLeisure,
  societyCulture,
  science,
  music,
  history,
  geography,
  generalKnowledge,
  foodDrink,
  filmTv,
  artsLiterature,
  availableCategories,
};
